<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Tc Execution is StartDefault test]]>
    </line>
    <line>
      <![CDATA[TC execution is started myMethod1]]>
    </line>
    <line>
      <![CDATA[myMethod1--> TC execution is started]]>
    </line>
    <line>
      <![CDATA[TC execution is successful myMethod1]]>
    </line>
    <line>
      <![CDATA[TC execution is started myMethod2]]>
    </line>
    <line>
      <![CDATA[TC execution is failed myMethod2]]>
    </line>
    <line>
      <![CDATA[TC execution is started myMethod3]]>
    </line>
    <line>
      <![CDATA[TC execution is skipped myMethod3]]>
    </line>
    <line>
      <![CDATA[TC execution is finish Default test]]>
    </line>
  </reporter-output>
  <suite started-at="2022-09-26T17:49:03 IST" name="Default suite" finished-at="2022-09-26T17:49:03 IST" duration-ms="51">
    <groups>
    </groups>
    <test started-at="2022-09-26T17:49:03 IST" name="Default test" finished-at="2022-09-26T17:49:03 IST" duration-ms="51">
      <class name="testNGListener.DemoClass">
        <test-method signature="myMethod1()[pri:0, instance:testNGListener.DemoClass@3ee37e5a]" started-at="2022-09-26T17:49:03 IST" name="myMethod1" finished-at="2022-09-26T17:49:03 IST" duration-ms="7" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC execution is started myMethod1]]>
            </line>
            <line>
              <![CDATA[myMethod1--> TC execution is started]]>
            </line>
            <line>
              <![CDATA[TC execution is successful myMethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod1 -->
        <test-method signature="myMethod2()[pri:0, instance:testNGListener.DemoClass@3ee37e5a]" started-at="2022-09-26T17:49:03 IST" name="myMethod2" finished-at="2022-09-26T17:49:03 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testNGListener.DemoClass.myMethod2(DemoClass.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TC execution is started myMethod2]]>
            </line>
            <line>
              <![CDATA[TC execution is failed myMethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod2 -->
        <test-method signature="myMethod3()[pri:0, instance:testNGListener.DemoClass@3ee37e5a]" started-at="2022-09-26T17:49:03 IST" name="myMethod3" finished-at="2022-09-26T17:49:03 IST" depends-on-methods="testNGListener.DemoClass.myMethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DemoClass.myMethod3()[pri:0, instance:testNGListener.DemoClass@3ee37e5a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DemoClass.myMethod3()[pri:0, instance:testNGListener.DemoClass@3ee37e5a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC execution is skipped myMethod3]]>
            </line>
            <line>
              <![CDATA[TC execution is finish Default test]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod3 -->
      </class> <!-- testNGListener.DemoClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
